# Generated by Django 4.2.13 on 2026-06-07 05:38

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='书名/文献名')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='作者')),
                ('dynasty', models.CharField(blank=True, max_length=100, verbose_name='朝代/年代')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='出版地/出版社')),
                ('volume', models.CharField(blank=True, max_length=50, verbose_name='卷/册')),
                ('page', models.CharField(blank=True, max_length=50, verbose_name='页码/篇目')),
                ('note', models.TextField(blank=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文献出处',
                'verbose_name_plural': '文献出处',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='PlaceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='地名')),
                ('alternative_name', models.CharField(blank=True, max_length=100, verbose_name='别名/简称')),
                ('region', models.CharField(blank=True, max_length=200, verbose_name='所属地区')),
                ('start_year', models.CharField(blank=True, max_length=50, verbose_name='始见年代')),
                ('end_year', models.CharField(blank=True, max_length=50, verbose_name='废止年代')),
                ('reliability', models.IntegerField(default=50, verbose_name='可信度')),
                ('description', models.TextField(blank=True, verbose_name='地名描述')),
                ('collation_status', models.CharField(choices=[('pending', '未校勘'), ('in_progress', '校勘中'), ('completed', '已完成')], default='pending', max_length=20, verbose_name='校勘状态')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '古地名',
                'verbose_name_plural': '古地名',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PlaceNameLiterature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_detail', models.CharField(blank=True, max_length=200, verbose_name='引用细节')),
                ('literature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.literature', verbose_name='文献出处')),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.placename', verbose_name='地名')),
            ],
            options={
                'verbose_name': '地名-文献关联',
                'verbose_name_plural': '地名-文献关联',
                'unique_together': {('place_name', 'literature')},
            },
        ),
        migrations.AddField(
            model_name='placename',
            name='literatures',
            field=models.ManyToManyField(through='places.PlaceNameLiterature', to='places.literature', verbose_name='文献出处'),
        ),
        migrations.CreateModel(
            name='NameRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_type', models.CharField(choices=[('alias', '异名'), ('error', '讹误'), ('evolution', '沿革'), ('belong_to', '隶属'), ('other', '其他')], default='alias', max_length=20, verbose_name='关系类型')),
                ('reliability', models.IntegerField(default=50, verbose_name='可信度')),
                ('confirmed', models.BooleanField(default=False, verbose_name='是否已确认')),
                ('description', models.TextField(blank=True, verbose_name='关系说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_a', to='places.placename', verbose_name='地名A')),
                ('name_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relations_as_b', to='places.placename', verbose_name='地名B')),
            ],
            options={
                'verbose_name': '异名关系',
                'verbose_name_plural': '异名关系',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='争议标题')),
                ('content', models.TextField(verbose_name='争议内容')),
                ('proposer', models.CharField(blank=True, max_length=100, verbose_name='提出者')),
                ('status', models.CharField(choices=[('open', '未解决'), ('resolved', '已解决')], default='open', max_length=20, verbose_name='状态')),
                ('resolution', models.TextField(blank=True, verbose_name='解决方案')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='解决日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='places.placename', verbose_name='地名')),
            ],
            options={
                'verbose_name': '争议记录',
                'verbose_name_plural': '争议记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='意见标题')),
                ('content', models.TextField(verbose_name='校勘内容')),
                ('conclusion', models.TextField(blank=True, verbose_name='校勘结论')),
                ('collator', models.CharField(blank=True, max_length=100, verbose_name='校勘人')),
                ('collation_date', models.DateField(default=django.utils.timezone.now, verbose_name='校勘日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collation_notes', to='places.placename', verbose_name='地名')),
            ],
            options={
                'verbose_name': '校勘意见',
                'verbose_name_plural': '校勘意见',
                'ordering': ['-collation_date'],
            },
        ),
    ]
