# Generated by Django 4.2.13 on 2026-06-07 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('place', '地名'), ('relation', '关系'), ('literature', '文献'), ('collation', '校勘意见'), ('dispute', '争议记录'), ('annotation', '批注'), ('deletion_request', '删除申请'), ('review', '审核记录')], max_length=30, verbose_name='目标类型')),
                ('target_id', models.IntegerField(blank=True, null=True, verbose_name='目标ID')),
                ('target_name', models.CharField(blank=True, max_length=200, verbose_name='目标名称')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '更新'), ('delete', '删除'), ('submit', '提交'), ('approve', '通过'), ('reject', '驳回'), ('resolve', '解决'), ('archive', '归档'), ('other', '其他')], max_length=20, verbose_name='操作类型')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='操作人')),
                ('detail', models.TextField(blank=True, verbose_name='操作详情')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP地址')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='dispute',
            name='reopen_count',
            field=models.IntegerField(default=0, verbose_name='重新开启次数'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolution_type',
            field=models.CharField(blank=True, choices=[('', '未解决'), ('evidence', '证据裁定'), ('vote', '投票表决'), ('expert', '专家裁定'), ('merged', '合并处理'), ('withdrawn', '撤回申请')], default='', max_length=20, verbose_name='解决方式'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='resolver',
            field=models.CharField(blank=True, max_length=100, verbose_name='处理人'),
        ),
        migrations.AddField(
            model_name='dispute',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='namerelation',
            name='proposer',
            field=models.CharField(blank=True, max_length=100, verbose_name='提出人'),
        ),
        migrations.AddField(
            model_name='namerelation',
            name='status',
            field=models.CharField(choices=[('proposed', '待确认'), ('confirmed', '已确认'), ('disputed', '有争议'), ('rejected', '已驳回')], default='proposed', max_length=20, verbose_name='关系状态'),
        ),
        migrations.AddField(
            model_name='placename',
            name='end_year_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='废止年(数值)'),
        ),
        migrations.AddField(
            model_name='placename',
            name='review_comment',
            field=models.TextField(blank=True, verbose_name='审核意见'),
        ),
        migrations.AddField(
            model_name='placename',
            name='review_status',
            field=models.CharField(choices=[('draft', '草稿'), ('submitted', '待审核'), ('reviewing', '审核中'), ('approved', '已通过'), ('rejected', '已驳回'), ('archived', '已归档')], default='draft', max_length=20, verbose_name='审核状态'),
        ),
        migrations.AddField(
            model_name='placename',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='审核时间'),
        ),
        migrations.AddField(
            model_name='placename',
            name='reviewer',
            field=models.CharField(blank=True, max_length=100, verbose_name='审核人'),
        ),
        migrations.AddField(
            model_name='placename',
            name='start_year_num',
            field=models.IntegerField(blank=True, null=True, verbose_name='始见年(数值)'),
        ),
        migrations.AddField(
            model_name='placename',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='提交时间'),
        ),
        migrations.AddField(
            model_name='placename',
            name='submitter',
            field=models.CharField(blank=True, max_length=100, verbose_name='提交人'),
        ),
        migrations.AlterField(
            model_name='dispute',
            name='status',
            field=models.CharField(choices=[('open', '处理中'), ('investigating', '调查中'), ('resolved', '已解决'), ('rejected', '已驳回'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态'),
        ),
        migrations.CreateModel(
            name='ReviewRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submit', '提交审核'), ('approve', '审核通过'), ('reject', '审核驳回'), ('archive', '归档'), ('reopen', '重新提交')], max_length=20, verbose_name='操作类型')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='操作人')),
                ('comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('place_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='places.placename', verbose_name='地名')),
                ('relation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review_records', to='places.namerelation', verbose_name='关系')),
            ],
            options={
                'verbose_name': '审核记录',
                'verbose_name_plural': '审核记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeletionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='删除理由')),
                ('applicant', models.CharField(blank=True, max_length=100, verbose_name='申请人')),
                ('status', models.CharField(choices=[('pending', '待审核'), ('reviewing', '审核中'), ('approved', '已批准'), ('rejected', '已驳回'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('reviewer', models.CharField(blank=True, max_length=100, verbose_name='审核人')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='执行时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='申请时间')),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deletion_requests', to='places.placename', verbose_name='地名')),
            ],
            options={
                'verbose_name': '删除申请',
                'verbose_name_plural': '删除申请',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_type', models.CharField(choices=[('place', '地名'), ('relation', '关系'), ('literature', '文献'), ('collation', '校勘意见'), ('dispute', '争议记录')], max_length=20, verbose_name='目标类型')),
                ('target_id', models.IntegerField(verbose_name='目标ID')),
                ('content', models.TextField(verbose_name='批注内容')),
                ('author', models.CharField(blank=True, max_length=100, verbose_name='批注人')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='是否已解决')),
                ('resolved_by', models.CharField(blank=True, max_length=100, verbose_name='解决人')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='解决时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('reply_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='places.annotation', verbose_name='回复给')),
            ],
            options={
                'verbose_name': '协作批注',
                'verbose_name_plural': '协作批注',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlaceNameVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1, verbose_name='版本号')),
                ('change_summary', models.TextField(default='{}', verbose_name='变更摘要')),
                ('change_fields', models.JSONField(default=list, verbose_name='变更字段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='places.placename', verbose_name='地名')),
            ],
            options={
                'verbose_name': '地名版本',
                'verbose_name_plural': '地名版本',
                'ordering': ['-version_number'],
                'unique_together': {('place_name', 'version_number')},
            },
        ),
    ]
