# Generated by Django 4.2.13 on 2026-06-07 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_operationlog_dispute_reopen_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deletionrequest',
            name='place_name_snapshot',
            field=models.CharField(blank=True, max_length=200, verbose_name='地名快照'),
        ),
        migrations.AlterField(
            model_name='deletionrequest',
            name='place_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deletion_requests', to='places.placename', verbose_name='地名'),
        ),
    ]
