# Generated by Django 4.2.13 on 2026-06-07 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_deletionrequest_place_name_snapshot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='迁移标题')),
                ('migration_type', models.CharField(choices=[('administrative', '行政变迁'), ('geographic', '地理迁移'), ('name_change', '名称变更'), ('boundary_change', '边界变动'), ('merge', '合并'), ('split', '拆分'), ('other', '其他')], default='administrative', max_length=20, verbose_name='迁移类型')),
                ('region', models.CharField(blank=True, max_length=200, verbose_name='所属地区')),
                ('dynasty', models.CharField(blank=True, max_length=100, verbose_name='朝代/年代')),
                ('start_year', models.CharField(blank=True, max_length=50, verbose_name='起始年代')),
                ('end_year', models.CharField(blank=True, max_length=50, verbose_name='结束年代')),
                ('start_year_num', models.IntegerField(blank=True, null=True, verbose_name='起始年(数值)')),
                ('end_year_num', models.IntegerField(blank=True, null=True, verbose_name='结束年(数值)')),
                ('reliability', models.IntegerField(default=50, verbose_name='可信度')),
                ('migration_reason', models.TextField(blank=True, verbose_name='迁移原因')),
                ('conclusion', models.TextField(blank=True, verbose_name='迁移结论')),
                ('has_dispute', models.BooleanField(default=False, verbose_name='存在争议')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('submitted', '待审核'), ('approved', '已通过'), ('rejected', '已驳回')], default='draft', max_length=20, verbose_name='状态')),
                ('submitter', models.CharField(blank=True, max_length=100, verbose_name='提交人')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('reviewer', models.CharField(blank=True, max_length=100, verbose_name='审核人')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='审核时间')),
                ('review_comment', models.TextField(blank=True, verbose_name='审核意见')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('place_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migrations', to='places.placename', verbose_name='关联地名')),
            ],
            options={
                'verbose_name': '时空迁移对照',
                'verbose_name_plural': '时空迁移对照',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='operationlog',
            name='target_type',
            field=models.CharField(choices=[('place', '地名'), ('relation', '关系'), ('literature', '文献'), ('collation', '校勘意见'), ('dispute', '争议记录'), ('annotation', '批注'), ('deletion_request', '删除申请'), ('review', '审核记录'), ('migration', '迁移对照')], max_length=30, verbose_name='目标类型'),
        ),
        migrations.CreateModel(
            name='MigrationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(max_length=200, verbose_name='阶段名称')),
                ('dynasty', models.CharField(blank=True, max_length=100, verbose_name='朝代/时期')),
                ('start_year', models.CharField(blank=True, max_length=50, verbose_name='起始年代')),
                ('end_year', models.CharField(blank=True, max_length=50, verbose_name='结束年代')),
                ('start_year_num', models.IntegerField(blank=True, null=True, verbose_name='起始年(数值)')),
                ('end_year_num', models.IntegerField(blank=True, null=True, verbose_name='结束年(数值)')),
                ('place_name_text', models.CharField(blank=True, max_length=100, verbose_name='当时地名')),
                ('administrative_division', models.CharField(blank=True, max_length=200, verbose_name='行政隶属')),
                ('region', models.CharField(blank=True, max_length=200, verbose_name='所属地区')),
                ('longitude', models.FloatField(blank=True, null=True, verbose_name='经度')),
                ('latitude', models.FloatField(blank=True, null=True, verbose_name='纬度')),
                ('coordinate_range', models.TextField(blank=True, verbose_name='坐标范围/四至')),
                ('description', models.TextField(blank=True, verbose_name='地理描述')),
                ('evidence', models.TextField(blank=True, verbose_name='证据说明')),
                ('reliability', models.IntegerField(default=50, verbose_name='可信度')),
                ('order_index', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('migration_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='places.migrationrecord', verbose_name='迁移记录')),
            ],
            options={
                'verbose_name': '迁移阶段',
                'verbose_name_plural': '迁移阶段',
                'ordering': ['order_index', 'start_year_num', 'start_year'],
            },
        ),
        migrations.CreateModel(
            name='MigrationEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citation_detail', models.CharField(blank=True, max_length=200, verbose_name='引用细节')),
                ('evidence_content', models.TextField(blank=True, verbose_name='证据内容')),
                ('evidence_type', models.CharField(blank=True, max_length=50, verbose_name='证据类型')),
                ('reliability', models.IntegerField(default=50, verbose_name='证据可信度')),
                ('order_index', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('literature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='migration_evidences', to='places.literature', verbose_name='文献出处')),
                ('migration_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='places.migrationrecord', verbose_name='迁移记录')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidences', to='places.migrationstage', verbose_name='关联阶段')),
            ],
            options={
                'verbose_name': '迁移证据',
                'verbose_name_plural': '迁移证据',
                'ordering': ['order_index', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationDispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='争议标题')),
                ('content', models.TextField(verbose_name='争议内容')),
                ('proposer', models.CharField(blank=True, max_length=100, verbose_name='提出者')),
                ('status', models.CharField(choices=[('open', '处理中'), ('investigating', '调查中'), ('resolved', '已解决'), ('rejected', '已驳回'), ('closed', '已关闭')], default='open', max_length=20, verbose_name='状态')),
                ('resolution', models.TextField(blank=True, verbose_name='解决方案')),
                ('resolver', models.CharField(blank=True, max_length=100, verbose_name='处理人')),
                ('resolved_date', models.DateField(blank=True, null=True, verbose_name='解决日期')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('migration_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='places.migrationrecord', verbose_name='迁移记录')),
                ('stage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes', to='places.migrationstage', verbose_name='关联阶段')),
            ],
            options={
                'verbose_name': '迁移争议',
                'verbose_name_plural': '迁移争议',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MigrationVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(default=1, verbose_name='版本号')),
                ('change_summary', models.TextField(default='{}', verbose_name='变更摘要')),
                ('change_fields', models.JSONField(default=list, verbose_name='变更字段')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('migration_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='places.migrationrecord', verbose_name='迁移记录')),
            ],
            options={
                'verbose_name': '迁移版本',
                'verbose_name_plural': '迁移版本',
                'ordering': ['-version_number'],
                'unique_together': {('migration_record', 'version_number')},
            },
        ),
    ]
