# Generated by Django 4.2.13 on 2026-06-07 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_migrationrecord_alter_operationlog_target_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiteratureComparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='比对任务名称')),
                ('description', models.TextField(blank=True, verbose_name='比对说明')),
                ('status', models.CharField(choices=[('pending', '待执行'), ('running', '执行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('total_places', models.IntegerField(default=0, verbose_name='比对地名数')),
                ('total_doubts', models.IntegerField(default=0, verbose_name='发现疑点')),
                ('operator', models.CharField(blank=True, max_length=100, verbose_name='执行人')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='开始时间')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '文献比对任务',
                'verbose_name_plural': '文献比对任务',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='annotation',
            name='target_type',
            field=models.CharField(choices=[('place', '地名'), ('relation', '关系'), ('literature', '文献'), ('collation', '校勘意见'), ('dispute', '争议记录'), ('doubt', '比对疑点'), ('collation_task', '校勘任务')], max_length=20, verbose_name='目标类型'),
        ),
        migrations.CreateModel(
            name='ComparisonDoubt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doubt_type', models.CharField(choices=[('same_name_diff_place', '同名异地'), ('diff_name_same_place', '异名同地'), ('year_conflict', '年代冲突'), ('region_conflict', '行政归属冲突'), ('coordinate_conflict', '坐标冲突'), ('reliability_abnormal', '可信度异常')], max_length=30, verbose_name='疑点类型')),
                ('severity', models.CharField(choices=[('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='严重程度')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('investigating', '调查中'), ('resolved', '已解决'), ('dismissed', '已忽略')], default='pending', max_length=20, verbose_name='处理状态')),
                ('title', models.CharField(max_length=200, verbose_name='疑点标题')),
                ('description', models.TextField(verbose_name='疑点描述')),
                ('conflict_detail', models.JSONField(default=dict, verbose_name='冲突详情')),
                ('evidence_data', models.JSONField(default=list, verbose_name='证据数据')),
                ('resolver', models.CharField(blank=True, max_length=100, verbose_name='处理人')),
                ('resolution', models.TextField(blank=True, verbose_name='处理结果')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='处理时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('comparison', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doubts', to='places.literaturecomparison', verbose_name='比对任务')),
                ('literature_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubts_as_a', to='places.literature', verbose_name='文献A')),
                ('literature_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubts_as_b', to='places.literature', verbose_name='文献B')),
                ('place_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubts_as_a', to='places.placename', verbose_name='地名A')),
                ('place_b', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doubts_as_b', to='places.placename', verbose_name='地名B')),
            ],
            options={
                'verbose_name': '比对疑点',
                'verbose_name_plural': '比对疑点',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CollationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('verify_doubt', '疑点核查'), ('check_literature', '文献查证'), ('correct_data', '数据修正'), ('supplement_info', '信息补充'), ('other', '其他')], default='verify_doubt', max_length=20, verbose_name='任务类型')),
                ('priority', models.CharField(choices=[('urgent', '紧急'), ('high', '高'), ('medium', '中'), ('low', '低')], default='medium', max_length=10, verbose_name='优先级')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('in_progress', '处理中'), ('completed', '已完成'), ('cancelled', '已取消')], default='pending', max_length=20, verbose_name='状态')),
                ('title', models.CharField(max_length=200, verbose_name='任务标题')),
                ('description', models.TextField(verbose_name='任务描述')),
                ('assignee', models.CharField(blank=True, max_length=100, verbose_name='指派给')),
                ('creator', models.CharField(blank=True, max_length=100, verbose_name='创建人')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='截止日期')),
                ('result', models.TextField(blank=True, verbose_name='处理结果')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完成时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('doubt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collation_tasks', to='places.comparisondoubt', verbose_name='关联疑点')),
                ('literature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collation_tasks', to='places.literature', verbose_name='关联文献')),
                ('place_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collation_tasks', to='places.placename', verbose_name='关联地名')),
            ],
            options={
                'verbose_name': '待校勘任务',
                'verbose_name_plural': '待校勘任务',
                'ordering': ['-priority', '-created_at'],
            },
        ),
    ]
